version: "3.4"

services:
  # DATABASE
  database:
    extends:
      file: database/db-service.yml
      service: database_service

  # REST API
  webapi:
    build: ./webapi
    ports:
      - "8501:8501"
    links:
      - database
