version: "3.9"

services:
  # DATABASE
  mongodb:
    image: mongo
    container_name: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      # MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    networks:
      - backend

    ports:
      - "27017:27017"

    command: [--auth]
    restart: unless-stopped

  # REST API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    environment:
      PORT_WEB: 5000
      HOST_WEB: "0.0.0.0"
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "interview"
      MONGODB_PASSWORD: "interview"
      MONGO_INITDB_DATABASE: webapp
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
