version: "3.7"

services:
  # DATABASE
  db:
    extends:
      file: db/db-service.yml
      service: db

  
  # REST API
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
     
    command: gunicorn --bind 0.0.0.0:8501 main:main
    ports:
      - "8501:8501"
    environment:
        MONGODB_HOST: mongodb
        MONGODB_USERNAME: "interview"
        MONGODB_PASSWORD: "interview"
    depends_on: 
        - db
    volumes:
        - appdata:/var/www/
    networks:
      - backend
      - frontend


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local