# DATABASE SERVICE
services:
  # DATABASE
  db:
    image: mongo:4.2.3 # stable
    restart: unless-stopped
    container_name: mongo
    command: mongod --auth

    environment:
      MONGO_INITDB_ROOT_USERNAME: "interview"
      MONGO_INITDB_ROOT_PASSWORD: "interview"
      MONGO_INITDB_DATABASE: webapp
      MONGODB_DATA_DIR: /data/db

    volumes: # DATABASE STORE
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/db:/usr/data/db
      - mongodbdata:/data/db
    
    ports:
      - "27017:27017"
    
    networks:
      - backend